### ISSUE TITLE
Stilts unable to read *mean_comp.fits due to column mismatch

### ISSUE THREAD

**Issue by gemmaanderson** [PaulHancock/Robbie#15]
The file *mean_comp.fits currently needs to be edited manually using TopCat so that the column for psf_pa is changed to a Float type rather than an Integer Type.

```
if [[ -n "monitor_grb180805a_28s.fits" ]] ;\
then java -jar /home/gemma/software/stilts.jar tcatn nin=2 in1=GRB180805A_28s_mean_comp.fits in2=monitor_grb180805a_28s.fits out=GRB180805A_28s_persistent_sources.fits ;\
else cp GRB180805A_28s_mean_comp.fits GRB180805A_28s_persistent_sources.fits ;\
fi
Error: Column type mismatch (psf_pa(Float) not compatible with psf_pa(Integer))
Makefile:157: recipe for target 'GRB180805A_28s_persistent_sources.fits' failed
make: *** [GRB180805A_28s_persistent_sources.fits] Error 1
```

**Comment by PaulHancock** [comment]
The error suggests that it's the `monitor_grb180805a_28s.fits` file which has the wrong column format.
`psf_pa` should be a float. Can you clarify which of the two files you edit to fix the issue?

**Comment by gemmaanderson** [comment]
The `monitor_grb180805a_28s.fits` file has `psf_pa` listed as a float. I think it is the `GRB180805A_28s_mean_comp.fits` that I have been editing so this value may be changing from a float to an integer when the comp.fits file is created? (I will check more closely next time I run this the whole way through.)

**Comment by PaulHancock** [comment]
Aegean has been updated to ensure that columns have a consistent data type, so that the `psf_pa` should always be a float, even when zero. I'll close this issue for now since I have not seen it in the nextflow version of Robbie. Please reopen if the issue returns.
