### ISSUE TITLE
incorporate flux_warp into Robbie

### ISSUE THREAD

**Issue by JunTian-CIRA** [PaulHancock/Robbie#20]
I suggest to incorporate flux_warp into Robbie so that we can correct the flux scale of images. The github repository of flux_warp is at https://gitlab.com/Sunmish/flux_warp, and the latest version works fine.

There are two commands in flux_warp:
1) match_catalogues ${prefix}-pbcorr-I_warped_comp.fits GLEAM_EGC_params.fits --separation 0.017 --exclusion_zone 0.017 --nmax 1000

The '${prefix}-pbcorr-I_warped_comp.fits' file is a catalogue of sources found by aegean after performing fits_warp. 'GLEAM_EGC_params.fits' is a cropped GLEAM catalogue for matching with the sources in the image, and has been included in the package. The maximum separation between matched sources is set to be 0.017deg (1arcmin), and no match would be made if multiple sources are situated close to a source (within a radius of 0.017deg). Only the first 1000 matched sources (ranked by int_flux) will be output (default name ${prefix}-pbcorr-I_warped_comp_GLEAM_EGC_params.fits).

2) flux_warp ${prefix}-pbcorr-I_warped_comp_GLEAM_EGC_params.fits ${prefix}-pbcorr-I_warped.fits --mode ${method} --outname ${prefix}-pbcorr-I_warped_${method}.fits --nmax 1000 --ignore_magellanic --amp "alpha_c" --index "beta_c" --curvature "gamma_c" --plot --nolatex --residual

'method' indicates the function used to model the flux correction. '--ignore_magellanic' is set to ignore some sources that are not well modelled in the reference catalogue. The next 3 options are to specify the column name in the matched catalogue. The last few options are to control the output plot.

**Comment by PaulHancock** [comment]
As of b6e7f2b `flux_warp` has been included in the docker container.
The above commands have not yet been included in the workflow.

**Comment by JunTian-CIRA** [comment]
Thank you. I will copy the original main.nf file and add new processes into it.

**Comment by PaulHancock** [comment]
You can test your commands using an interactive singularity container in the following way:
```
salloc
env - PATH="$PATH" singularity shell /group/mwasci/phancock/.singularity/robbie-next_manual-2.1.4.sif
```

salloc will get you an interactive node on Pawsey (and not use the login node for processing)

the second command will give you a singularity shell that is isolated from the Pawsey environment so that any bugs are due to code within the container or scripts that you are using

**Comment by JunTian-CIRA** [comment]
Paul, I can't access the robbie-next_manual-2.1.4.sif file, permission denied.
