### ISSUE TITLE
params.monitor=false causes error in sfind_mean_image

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Robbie#23]
`params.monitor` should be a file name when monitoring is to be done. If this is set to empty or `false` then Robbie will crash.

Suggestion:
`params.do_monitoring=true/false` to turn on/off the monitoring and then use `params.monitor_file` to point to the file if monitoring is being done.

Also:
do a similar change for the `params.region_file` so that it can be included or not without having to hack the `main.nf` file.

**Comment by NickSwainston** [comment]
Looks like this has already been fixed
