### ISSUE TITLE
get_epoch.py: command not found

### ISSUE THREAD

**Issue by JunTian-CIRA** [PaulHancock/Robbie#24]
This command is yet to be added to the container.

**Comment by JunTian-CIRA** [comment]
A kind reminder that this issue is yet to be fixed.

**Comment by PaulHancock** [comment]
Since 30bfd5d `get_epoch.py` is now included in the docker container.
`get_lc_from_vot.py` has also been included, and the singularity image on Pawsey has been updated.

**Comment by PaulHancock** [comment]
@JunTian-CIRA Once you confirm that the error is fixed, please close this issue.
