### ISSUE TITLE
running nextflow on Magnus

### ISSUE THREAD

**Issue by JunTian-CIRA** [PaulHancock/Robbie#25]
Running nextflow on Magnus reports the error below:
![Screenshot from 2020-04-22 10-47-29](https://user-images.githubusercontent.com/53510317/79935132-b7a8d280-8486-11ea-9edc-ea707cdac532.png)

**Comment by PaulHancock** [comment]
Does this same workflow run on Zeus? eg, is this a Magnus problem, or is this a general problem?

**Comment by JunTian-CIRA** [comment]
It works fine on Zeus. I don't know why the docker need astropy module, even after I loaded it to Magnus.

**Comment by PaulHancock** [comment]
Ok this seems like some magnus specific thing. I'll submit a help desk ticket and see what I can do.

**Comment by JunTian-CIRA** [comment]
Yes, I noticed some latest change to Magnus environment, which even failed our imaging pipeline.

**Comment by PaulHancock** [comment]
in the singularity section of the config file use `envWhitelist = 'SINGULARITY_BINDPATH, SINGULARITYENV_LD_LIBRARY_PATH'`
This should make it possible to run Robbie on both Magnus and Zeus.
