### ISSUE TITLE
error while making flux table

### ISSUE THREAD

**Issue by jvchauhan** [PaulHancock/Robbie#9]
# getting error
ndof=($(./auto_corr.py cube.fits)) ;\
./calc_var.py --infile flux_table.fits --outfile flux_table_var.fits --ndof 
./plot_lc.py flux_table_var.fits
usage: calc_var.py [-h] [--infile INFILE] [--outfile OUTFILE] [--ndof NDOF]
calc_var.py: error: argument --ndof: expected one argument

# then try

# add variability stats to the flux table
$(PREFIX)flux_table_var.fits: $(PREFIX)flux_table.fits
	ndof=($$(./auto_corr.py $(PREFIX)cube.fits)) ;\
	./calc_var.py --infile $< --outfile $@ --ndof $${ndof[-1]}
	./plot_lc.py $@
# and it is fixed

**Comment by PaulHancock** [comment]
This is for the `make` version of Robbie which is no longer being developed.
